parameters:

    swoole_bridge.handler.class: Insidestyles\SwooleBridge\Handler
    swoole_bridge.adapter.symfony.class: Insidestyles\SwooleBridge\Adapter\SymfonyAdapter
    swoole_bridge.factory.request_builder.class: Insidestyles\SwooleBridge\Builder\RequestBuilderFactory
    swoole_bridge.emitter.class: Insidestyles\SwooleBridge\Emiter\SwooleResponseEmitter
    swoole_bridge.psr15_symfony_kernel.class: Insidestyles\SwooleBridge\Adapter\Kernel\Psr15SymfonyKernel

services:

    swoole_bridge.emitter:
        class: "%swoole_bridge.emitter.class%"

    swoole_bridge.factory.request_builder:
        class: "%swoole_bridge.factory.request_builder.class%"

    swoole_bridge.psr15_symfony_kernel:
        class: "%swoole_bridge.psr15_symfony_kernel.class%"
        arguments:
            - "@kernel"

    swoole_bridge.adapter.symfony:
        class: "%swoole_bridge.adapter.symfony.class%"
        arguments:
            - "@swoole_bridge.emitter"
            - "@swoole_bridge.psr15_symfony_kernel"
            - "@swoole_bridge.factory.request_builder"

    swoole_bridge.handler:
        class: "%swoole_bridge.handler.class%"
        arguments:
            - "@swoole_bridge.adapter.symfony"
            - "@?logger"

    swoole_bridge.server_command:
        class: Insidestyles\SwooleBridgeBundle\Command\SwooleBridgeServerCommand
        arguments:
            - "@swoole_bridge.handler"
            - "%swoole_bridge.server.host%"
            - "%swoole_bridge.server.port%"
        tags:
            - { name: console.command }
